name: asr_live_translator
description: Live ASR transcripts with TTS, latest output only.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^4.0.1
  http: ^1.3.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  flutter_tts: ^4.2.5
  share_plus: ^7.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true